variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375

stages:
  - deploy

image:
  name: docker:23.0.5

services:
  - name: docker:23.0.5-dind
    alias: docker

deploy:
  stage: deploy
  before_script:
    - export DOCKER_CLI_EXPERIMENTAL=enabled
  script:
    - docker compose -f docker-compose.yml up -d
