variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375

stages:
  - deploy

image:
  name: docker:23.0.5

services:
  - name: docker:23.0.5-dind
    alias: docker

deploy:
  stage: deploy
  before_script:
    - export DOCKER_CLI_EXPERIMENTAL=enabled
    - |
      # Wait for Docker service to be ready
      while ! docker info > /dev/null 2>&1; do
        echo "Waiting for Docker to be ready..."
        sleep 1
      done
  script:
    - docker compose -f docker-compose.yml up -d
