variables:
  DOCKER_DRIVER: overlay2

stages:
  - deploy

image:
  name: docker:23.0.5

services:
  - docker:23.0.5-dind

deploy:
  stage: deploy
  before_script:
      - apt-get update && apt-get install -y python3-pip
      - pip3 install pytest requests
  
  script:
    - docker compose -f "docker-compose.yml" up -d --build
    - pytest -v --tb=no tests/test-api.py
  after_script:
    - docker-compose -f "docker-compose.yml" down
