stages:
  - test

variables:
  DOCKER_COMPOSE_FILE: "docker-compose.yml"
  DOCKER_HOST: "tcp://docker:2375"

before_script:
  - apt-get update && apt-get install -y python3-pip docker-compose || apk add --no-cache python3 py3-pip docker-compose
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install --no-cache-dir pytest requests

test:
  stage: test
  services:
    - name: docker:dind
      alias: docker
  script:
    - source venv/bin/activate
    - docker-compose -f "$DOCKER_COMPOSE_FILE" up -d --build
    - pytest -v --tb=no tests/test-api.py
  after_script:
    - docker-compose -f "$DOCKER_COMPOSE_FILE" down
  timeout: 10m