name: Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  docker:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker compose -f "docker-compose.yml" up -d --build

    - name: Install requirements
      run: pip install pytest requests

    - name: Run tests
      run: pytest -v --tb=no tests/test-api.py

    # - name: Clean teamengine container
    #   run: docker stop teamengine || true && docker rm teamengine || true

    # - name: Run team engine
    #   run: docker run -d --rm --name=teamengine --network=host ogccite/teamengine-production:1.0-SNAPSHOT
            
    - name: test ogcapi-features compliance
      uses: OSGEO/cite-runner@main
      with:
        test_suite_identifier: ogcapi-features-1.0
        test_session_arguments: >-
          iut=http://localhost:5000
          noofcollections=-1

    - name: Stop containers
      if: always()
      run: docker compose -f "docker-compose.yml" down -v